[project]
name = "silentsheet"
version = "2.2.4"
description = "Automate Ultimatix timesheet login via EasyAuth"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pillow>=11.2.1",
    "pratikpathak>=2.3.5",
    "selenium>=4.41.0",
    "winotify>=1.1.0",
]

[project.scripts]
silentsheet = "fill_timesheet:main"
